# Generated by Django 2.0.2 on 2018-02-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sake_recommender', '0002_auto_20180215_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sake',
            old_name='_type',
            new_name='sake_type',
        ),
    ]
